#!/usr/bin/php -q
<?php

require_once __DIR__.'/src/autoload.php';
use Lessphp\Lessify;

if (php_sapi_name() != "cli") { 
	err($fa.$argv[0]." must be run in the command line.");
	exit(1);
}
$exe = array_shift($argv); // remove filename

if (!$fname = array_shift($argv)) {
	exit("Usage: ".$exe." input-file\n");
}


try  {
	$parser = new Lessify($fname);
	echo $parser->parse();
} catch (Exception $e) {
	exit("Fatal error: ".$e->getMessage()."\n");
}


